baseURL = "https://prajwal-banakar.github.io/"
title = "Prajwal Banakar"
theme = "PaperMod"

[params]
  author = "Prajwal Banakar"
  description = "Apache Fluss Contributor | Distributed Systems | Open Source"

[menu]
  [[menu.main]]
    name = "Posts"
    url = "/posts/"
    weight = 1

  [[menu.main]]
    name = "Projects"
    url = "/projects/"
    weight = 2

  [[menu.main]]
    name = "About"
    url = "/about/"
    weight = 3
